name: Backend Build & Push

on:
  workflow_run:
    workflows: ["PR checks"]
    types:
      - completed

env:
  DOCKERHUB_USER: suzal777
  VERSION: 1.0.0

jobs:
  check-backend-change:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Backend Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'code/backend1/**'
              - 'code/backend2/**'

  build-and-push-backend:
    runs-on: [backend]
    needs: check-backend-change
    if: ${{ needs.check-backend-change.outputs.changed == 'true' }}
    environment:
      name: ${{ github.event.workflow_run.head_branch == 'main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Backend1
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo ${{ github.event.workflow_run.head_branch }} | tr '/' '-')
          if [[ "$BRANCH_NAME" == "main" ]]; then
            docker build -t $DOCKERHUB_USER/backend1:latest -t $DOCKERHUB_USER/backend1:v${VERSION} ./code/backend1
            docker push $DOCKERHUB_USER/backend1:latest
            docker push $DOCKERHUB_USER/backend1:v${VERSION}
          else
            docker build -t $DOCKERHUB_USER/backend1:$BRANCH_NAME-$SHORT_SHA ./code/backend1
            docker push $DOCKERHUB_USER/backend1:$BRANCH_NAME-$SHORT_SHA
          fi

      - name: Build and Push Backend2
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo ${{ github.event.workflow_run.head_branch }} | tr '/' '-')
          if [[ "$BRANCH_NAME" == "main" ]]; then
            docker build -t $DOCKERHUB_USER/backend2:latest -t $DOCKERHUB_USER/backend2:v${VERSION} ./code/backend2
            docker push $DOCKERHUB_USER/backend2:latest
            docker push $DOCKERHUB_USER/backend2:v${VERSION}
          else
            docker build -t $DOCKERHUB_USER/backend2:$BRANCH_NAME-$SHORT_SHA ./code/backend2
            docker push $DOCKERHUB_USER/backend2:$BRANCH_NAME-$SHORT_SHA
          fi
