name: Backend Build & Push with SemVer

on:
  push:
    branches: [main]
    paths:
      - 'code/backend1/src/**'
      - 'code/backend2/src/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'code/backend1/src/**'
      - 'code/backend2/src/**'

env:
  DOCKERHUB_USER: suzal777

jobs:
  check-backend-change:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.backend == 'true' }}
      backend1_changed: ${{ steps.filter.outputs.backend1 == 'true' }}
      backend2_changed: ${{ steps.filter.outputs.backend2 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Backend Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'code/backend1/**'
              - 'code/backend2/**'
            backend1:
              - 'code/backend1/**'
            backend2:
              - 'code/backend2/**'

  check-dev-merge:
    runs-on: ubuntu-latest
    needs: check-backend-change
    if: |
      github.ref == 'refs/heads/main' &&
      needs.check-backend-change.outputs.changed == 'true'
    outputs:
      is_dev_merge: ${{ steps.check-merge.outputs.is_dev_merge }}
    steps:
      - name: Check if merge from dev
        id: check-merge
        run: |
          if [ "${{ github.event_name }}" = "push" ] && 
             [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "is_dev_merge=true" >> $GITHUB_OUTPUT
          else
            echo "is_dev_merge=false" >> $GITHUB_OUTPUT
          fi

  pr-checks:
    name: PR Research Checks
    runs-on: ubuntu-latest
    needs: check-backend-change
    if: |
      needs.check-backend-change.outputs.changed == 'true' &&
      (github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules (backend1)
        if: needs.check-backend-change.outputs.backend1_changed == 'true'
        uses: actions/cache@v3
        with:
          path: code/backend1/node_modules
          key: ${{ runner.os }}-backend1-node-${{ hashFiles('code/backend1/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-backend1-node-

      - name: Cache node modules (backend2)
        if: needs.check-backend-change.outputs.backend2_changed == 'true'
        uses: actions/cache@v3
        with:
          path: code/backend2/node_modules
          key: ${{ runner.os }}-backend2-node-${{ hashFiles('code/backend2/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-backend2-node-

      - name: Install TSLint
        run: npm install -g tslint typescript

      - name: Run TSLint (backend1)
        if: needs.check-backend-change.outputs.backend1_changed == 'true'
        working-directory: ./code/backend1
        run: |
          yarn install --frozen-lockfile
          tslint -c tslint.json 'src/**/*.{ts,js}' 'test/**/*.{ts,js}' || exit 1

      - name: Run TSLint (backend2)
        if: needs.check-backend-change.outputs.backend2_changed == 'true'
        working-directory: ./code/backend2
        run: |
          yarn install --frozen-lockfile
          tslint -c tslint.json 'src/**/*.{ts,js}' 'test/**/*.{ts,js}' || exit 1

  build-and-push-backend-dev:
    runs-on: [backend]
    needs: [check-backend-change, pr-checks]
    if: |
      needs.check-backend-change.outputs.changed == 'true' &&
      (github.event_name != 'pull_request' || needs.pr-checks.result == 'success') &&
      github.ref != 'refs/heads/main'
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Backend1
        if: needs.check-backend-change.outputs.backend1_changed == 'true'
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo $GITHUB_REF_NAME | tr '/' '-')
          
            docker build \
              -t $DOCKERHUB_USER/backend1:$BRANCH_NAME-$SHORT_SHA \
              ./code/backend1
            docker push $DOCKERHUB_USER/backend1:$BRANCH_NAME-$SHORT_SHA
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend2
        if: needs.check-backend-change.outputs.backend2_changed == 'true'
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo $GITHUB_REF_NAME | tr '/' '-')
          
            docker build \
              -t $DOCKERHUB_USER/backend2:$BRANCH_NAME-$SHORT_SHA \
              ./code/backend2
            docker push $DOCKERHUB_USER/backend2:$BRANCH_NAME-$SHORT_SHA
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker logout
        if: always()
        run: docker logout

  build-and-push-backend-main:
    runs-on: [backend]
    needs: [pr-checks, check-dev-merge]
    if: |
      github.ref == 'refs/heads/main' &&
      needs.check-dev-merge.outputs.is_dev_merge == 'true'
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Get Semantic Version
        id: semver
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
          tag_prefix: "v"
          create_annotated_tag: true
          dry_run: false
          default_bump: "patch"

      - name: Build and Push Backend1
        if: needs.check-backend-change.outputs.backend1_changed == 'true'
        env:
          VERSION: ${{ steps.semver.outputs.new_tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -z "$VERSION" ]]; then
            echo "ERROR: Version not determined!"
            exit 1
          fi

          echo "Building version: $VERSION"

            docker build \
              -t $DOCKERHUB_USER/backend1:latest \
              -t $DOCKERHUB_USER/backend1:$VERSION \
              ./code/backend1
            docker push $DOCKERHUB_USER/backend1:latest
            docker push $DOCKERHUB_USER/backend1:$VERSION
            
            if [[ "${{ needs.check-backend-change.outputs.backend2_changed }}" == "false" ]]; then
              gh release create v$VERSION \
                --title "Backend Release v$VERSION" \
                --notes "Production release from dev merge" \
                --target main
            fi

      - name: Build and Push Backend2
        if: needs.check-backend-change.outputs.backend2_changed == 'true'
        env:
          VERSION: ${{ steps.semver.outputs.new_tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -z "$VERSION" ]]; then
            echo "ERROR: Version not determined!"
            exit 1
          fi

          echo "Building version: $VERSION"

            docker build \
              -t $DOCKERHUB_USER/backend2:latest \
              -t $DOCKERHUB_USER/backend2:$VERSION \
              ./code/backend2
            docker push $DOCKERHUB_USER/backend2:latest
            docker push $DOCKERHUB_USER/backend2:$VERSION
            
            if [[ "${{ needs.check-backend-change.outputs.backend1_changed }}" == "false" ]]; then
              gh release create v$VERSION \
                --title "Backend Release v$VERSION" \
                --notes "Production release from dev merge" \
                --target main
            fi

      - name: Docker logout
        if: always()
        run: docker logout      