name: Docker Build & Push

on:
  push:
    branches: [main, dev]

env:
  DOCKERHUB_USER: suzal777

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          docker build -t $DOCKERHUB_USER/frontend:latest ./code/frontend
          docker push $DOCKERHUB_USER/frontend:latest

      - name: Build and Push Backend1
        run: |
          docker build -t $DOCKERHUB_USER/backend1:latest ./code/backend1
          docker push $DOCKERHUB_USER/backend1:latest

      - name: Build and Push Backend2
        run: |
          docker build -t $DOCKERHUB_USER/backend2:latest ./code/backend2
          docker push $DOCKERHUB_USER/backend2:latest
