name: Docker Build & Push

on:
  push:
    branches: [main, dev]
    paths: 
      - "code/**" 
      - "!.github/workflows/docker-build-push.yml"

  pull_request:
    branches: [dev]
    paths: "code/**"
    types: [opened, synchronize, reopened]

env:
  DOCKERHUB_USER: suzal777
  VERSION: 1.0.0

jobs:
  commit-lint:
    if: github.event_name == 'pull_request'
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            style
            perf
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-checks:
    if: github.event_name == 'pull_request'
    name: PR Research Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint
        run: npm install -g eslint

      - name: Run ESLint (frontend)
        working-directory: ./code/frontend
        run: |
          yarn install --frozen-lockfile
          yarn lint

      - name: Install TSLint
        run: npm install -g tslint typescript

      - name: Run TSLint (backend1)
        working-directory: ./code/backend1
        run: |
          yarn install --frozen-lockfile
          tslint -c tslint.json 'src/**/*.{ts,js}' 'test/**/*.{ts,js}' || exit 1

      - name: Run TSLint (backend2)
        working-directory: ./code/backend2
        run: |
          yarn install --frozen-lockfile
          tslint -c tslint.json 'src/**/*.{ts,js}' 'test/**/*.{ts,js}' || exit 1

  build-and-push-frontend:
    if: github.event_name == 'push'
    
    runs-on: [frontend]

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo $GITHUB_REF_NAME)
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            docker build -t $DOCKERHUB_USER/frontend:latest -t $DOCKERHUB_USER/frontend:v${VERSION} ./code/frontend
            docker push $DOCKERHUB_USER/frontend:latest
            docker push $DOCKERHUB_USER/frontend:v${VERSION}
          else
            docker build -t $DOCKERHUB_USER/frontend:$BRANCH_NAME-$SHORT_SHA ./code/frontend
            docker push $DOCKERHUB_USER/frontend:$BRANCH_NAME-$SHORT_SHA
          fi

  build-and-push-backend:
    if: github.event_name == 'push'
    runs-on: [backend]
  
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Backend1
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo $GITHUB_REF_NAME)
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            docker build -t $DOCKERHUB_USER/backend1:latest -t $DOCKERHUB_USER/backend1:v${VERSION} ./code/backend1
            docker push $DOCKERHUB_USER/backend1:latest
            docker push $DOCKERHUB_USER/backend1:v${VERSION}
          else
            docker build -t $DOCKERHUB_USER/backend1:$BRANCH_NAME-$SHORT_SHA ./code/backend1
            docker push $DOCKERHUB_USER/backend1:$BRANCH_NAME-$SHORT_SHA
          fi

      - name: Build and Push Backend2
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo $GITHUB_REF_NAME)
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            docker build -t $DOCKERHUB_USER/backend2:latest -t $DOCKERHUB_USER/backend2:v${VERSION} ./code/backend2
            docker push $DOCKERHUB_USER/backend2:latest
            docker push $DOCKERHUB_USER/backend2:v${VERSION}
          else
            docker build -t $DOCKERHUB_USER/backend2:$BRANCH_NAME-$SHORT_SHA ./code/backend2
            docker push $DOCKERHUB_USER/backend2:$BRANCH_NAME-$SHORT_SHA
          fi
            
