name: Frontend Build & Push

on:
  push:
    branches: [main, dev, feature/*]
    paths:
      - 'code/frontend/**'

  pull_request:
    branches: [dev, feature/*]
    paths:
      - 'code/frontend/**'

  workflow_run:
    workflows: ["PR checks"]
    types:
      - completed    

env:
  DOCKERHUB_USER: suzal777
  VERSION: 1.0.0

jobs:
  check-frontend-change:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Frontend Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'code/frontend/**'

  build-and-push-frontend:
    runs-on: [frontend]
    needs: check-frontend-change

    if: ${{ github.event_name != 'workflow_run' || needs.check-frontend-change.outputs.changed == 'true' }}

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo $GITHUB_REF_NAME)
          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            docker build -t $DOCKERHUB_USER/frontend:latest -t $DOCKERHUB_USER/frontend:v${VERSION} ./code/frontend
            docker push $DOCKERHUB_USER/frontend:latest
            docker push $DOCKERHUB_USER/frontend:v${VERSION}
          else
            docker build -t $DOCKERHUB_USER/frontend:$BRANCH_NAME-$SHORT_SHA ./code/frontend
            docker push $DOCKERHUB_USER/frontend:$BRANCH_NAME-$SHORT_SHA
          fi
