name: Frontend Build & Push

on:
  workflow_run:
    workflows: ["PR checks"]
    types:
      - completed

env:
  DOCKERHUB_USER: suzal777
  VERSION: 1.0.0

jobs:
  check-frontend-change:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Frontend Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'code/frontend/**'

  build-and-push-frontend:
    runs-on: [frontend]
    needs: check-frontend-change
    if: ${{ needs.check-frontend-change.outputs.changed == 'true' }}
    environment:
      name: ${{ github.event.workflow_run.head_branch == 'main' && 'production' || 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Frontend
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_NAME=$(echo ${{ github.event.workflow_run.head_branch }} | tr '/' '-')
          if [[ "$BRANCH_NAME" == "main" ]]; then
            docker build --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }} -t $DOCKERHUB_USER/frontend:latest -t $DOCKERHUB_USER/frontend:v${VERSION} ./code/frontend
            docker push $DOCKERHUB_USER/frontend:latest
            docker push $DOCKERHUB_USER/frontend:v${VERSION}
          else
            docker build --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }} -t $DOCKERHUB_USER/frontend:$BRANCH_NAME-$SHORT_SHA ./code/frontend
            docker push $DOCKERHUB_USER/frontend:$BRANCH_NAME-$SHORT_SHA
          fi
