name: PR checks

on:
  pull_request:
    branches: [dev]
    paths:
      - 'code/frontend/**'
      - 'code/backend1/**'
      - 'code/backend2/**'  

jobs:
  commit-lint:
    name: Check Conventional Commits
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            style
            perf
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
